repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.15
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
        files: ^((pypck|tests)/.+)?[^/]+\.(py|pyi)$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=authentification,SHS
          - --quiet-level=2
  - repo: local
    hooks:
    - id: mypy
      name: mypy pypck
      entry: uv run mypy
      language: system
      require_serial: true
      args:
        - --strict
        - -v
      files: ^(pypck)/.+\.py$
    - id: mypy
      name: mypy tests
      entry: uv run mypy
      language: system
      require_serial: true
      args:
        - --strict
        - -v
      files: ^(tests)/.+\.py$
