repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
        files: ^((pypck|tests)/.+)?[^/]+\.(py|pyi)$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=authentification,SHS
          - --quiet-level=2
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        name: mypy pypck
        args:
          - --strict
        files: ^(pypck)/.+\.py$
      - id: mypy
        name: mypy tests
        args:
          - --strict
          - --allow-untyped-defs
        files: ^(tests)/.+\.py$
        # Need to enumerate the deps with type hints since requirements.txt is
        # not read by pre-commit
        additional_dependencies:
          - pytest==8.3.1
          - pytest-cov==5.0.0
          - pytest-timeout==2.3.1
          - pytest-asyncio==0.23.8
