name: "Release actions"

on:
  release:
    types: ["published"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to PyPi
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: .python-version
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set version number from tag
        run: |
          uv version ${{ github.ref_name }}
      - name: Build distribution
        run: |
          uv build
      - name: Publish to PyPi
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          uv publish
